
name: 'observability'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  flex_observability:
    +materialized: table
    tags: ['observability']
    +schema: observability
    staging:
      +materialized: view
      tags: ['observability']
      +schema: observability
    views:
      +materialized: view
      tags: ['observability']
      +schema: observability
  elementary:
    +materialized: table
    tags: ['observability']
    +schema: 'observability_base'
