select
    unique_id,
    database_name,
    schema_name,
    name as test_name,
    short_name as test_category,
    alias,
    test_column_name,
    lower(severity) as configured_severity,
    warn_if,
    error_if,
    test_params,
    test_namespace,
    model_tags,
    tags,
    model_owners,
    meta,
    depends_on_macros,
    depends_on_nodes,
    parent_model_unique_id,
    cast(description as varchar(65535)) as description,
    package_name,
    original_path,
    type,
    cast(generated_at as datetime) as generated_at,
    path,
    metadata_hash,
    quality_dimension
from {{ source('observability', 'dbt_tests') }}
